#!/usr/bin/env sh
# AUTHOR: Aerex
# DESC:   Copy credentials with fzf and pass like rofi-pass
# DEPEND: fzf pass 

# Need to move this function into its own file
USERNAME_FZF_PASS_PREFIX=${USERNAME_FZF_PASS_PREFIX:-login:}
URL_FZF_PASS_PREFIX=${URL_FZF_PASS_PREFIX:-url:}

function copy_pass_safe() {
    echo "pass $1"
    if [[ ! -z $clipboard_manager ]]; then
      case "${clipboard_manager}" in
        greenclip) 
          ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -20
          greenclip print ''
          ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -18
          ;;
        esac
    fi
    pass "$1" | head -n 1 | xsel --clipboard --input
}

tree -fia ~/.password-store | grep '.gpg' | sed 's/^.\///' | sed "s|$HOME/.password-store/||g" | sed 's/.gpg//' | fzf -e -i -m --reverse --header="enter=copy password, ctrl-u=copy username, ctrl-l=copy url,ctrl-o=copy otp"  \
    --bind="ctrl-u:execute-silent[pass {} | grep ^$USERNAME_FZF_PASS_PREFIX | sed \"s/$USERNAME_FZF_PASS_PREFIX//\" | tr -d ' '  | xsel --clipboard --input]+abort" \
    --bind="ctrl-l:execute-silent[pass {} | grep ^$URL_FZF_PASS_PREFIX| sed \"s/$URL_FZF_PASS_PREFIX//\" | tr -d ' '  | xsel --clipboard --input]+abort" \
    --bind="ctrl-o:execute-silent[pass otp {} | tail -n 1 | tr -d '\n' | xsel --clipboard --input]+abort" \
    --bind="enter:execute-silent[pass {} | head -n 1 | tr -d '\n' | xsel --clipboard --input]+abort" 

