#!/usr/bin/env bash
# AUTHOR: Aerex
# DESC:   Copy credentials with fzf and pass like rofi-pass
# DEPEND: fzf pass 

# Need to move this function into its own file
function copy_pass_safe() {
    echo "pass $1"
    if [[ ! -z $clipboard_manager ]]; then
      case "${clipboard_manager}" in
        greenclip) 
          ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -20
          greenclip print ''
          ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -18
          ;;
        esac
    fi
    pass "$1" | head -n 1 | xsel --clipboard --input
}
function fzf_all_content() {
  ENTRY=$1
  selected=$(pass $ENTRY | fzf --reverse | cut -d: -f 2 | tr -d " ")
  echo "$selected" | xsel --clipboard --input
}

USERNAME_PREFIX="login:"
URL_PREFIX="url:"

mapfile -d '' _fhelp <<-EOF
Enter   Copy Password
Alt-u   Copy Username
Alt-o   Copy OTP
Alt-l   Copy URL
EOF

pass "$1" >/dev/null 2>&1 || exit 1
tree -fia ~/.password-store | grep '.gpg' | sed 's/^.\///' | sed "s|$HOME/.password-store/||g" | sed 's/.gpg//' | fzf -e -i -m --reverse --header="${_fhelp[0]}"  \
    --no-multi \
    --print-query\
    --bind="alt-u:execute-silent[pass {} | grep ^$USERNAME_PREFIX | sed \"s/$USERNAME_PREFIX//\" | tr -d ' '  | xsel --clipboard --input]+abort" \
    --bind="alt-l:execute-silent[pass {} | grep ^$URL_PREFIX | sed \"s/$URL_PREFIX//\" | tr -d ' '  | xsel --clipboard --input]+abort" \
    --bind="alt-o:execute-silent[pass otp {} | xsel --clipboard --input]+abort" \
    --bind="enter:execute-silent[pass {} | head -n 1 | tr -d '\n' | xsel --clipboard --input]+abort"  \
    --bind="tab:execute(pass {} | fzf --reverse | cut -d: -f 2 | tr -d ' ' | xsel --clipboard --input)+abort"
