#!/usr/bin/env bash
# AUTHOR: Aerex
# DESC:   Capture a screenshot of the screen

# TODO: Need to figure out why flameshot gui 
# changes the cursor style after closing app
if command -v flameshot >/dev/null; then
  setsid flameshot gui -d 500 -p $HOME/Pictures
elif command -v gnome-screenshot >/dev/null; then
  setsid gnome-screenshot -i 
  pkill --full st\ -t\ fzfnova
elif command -v scrot >/dev/null; then
  scrot -s
  echo "scrot impl not yet added"
  # TODO: Provide options to either capture window, whole screen, timed, etc
fi
pkill --full st\ -t\ fzfnova
