#!/usr/bin/env python3
#
# Behavior:
#   Userscript for qutebrowser which yanks the path from a url 
#   Dependencies: pyperclip
#   Example:
#       :spawn --userscript yank-url-path

import os
import sys
from urllib.parse import urlparse
import pyperclip

def qute_command(command):
    with open(os.environ['QUTE_FIFO'], 'w') as fifo:
        fifo.write(command + '\n')
        fifo.flush()


def main():
    try:
        QUTE_URL = os.getenv('QUTE_URL')
        extracted_url = urlparse(QUTE_URL)
        path = extracted_url.path[1:]
        pyperclip.copy(path)
        qute_command('message-info "Succesfully copied path {} from url {} to clipboard"'.format(path, QUTE_URL))
        return 0
    except Exception as e:
        qute_command('message-error "Failed to copy path of {} to clipboard"'.format(QUTE_URL))
        raise e

if __name__ == '__main__':
    sys.exit(main())
