#!/bin/bash

set -x
NEW_UNREAD_MESSAGE="$1"
MAIL_BOX_TITLE="$2"


# Default to use notify-send
OS=$(uname -s)
if [[ $OS == 'Linux' ]]; then
  # notify-send '$MAIL_BOX_TITLE' '$NUM_NEW_MESGS' new messages, '$NUM_UNREAD_MESGS' unread.' &
  notify-send "$MAIL_BOX_TITLE" "$NEW_UNREAD_MESSAGE"
elif [[ $OS == 'Darwin' ]]; then
  osascript -e 'display notification "'$NEW_UNREAD_MESSAGE'" with title "\"'$MAIL_BOX_TITLE'\""'
else
  notify-send "$MAIL_BOX_TITLE" "$NEW_UNREAD_MESSAGE"
fi


