#!/bin/bash

TMP_MUTT_ATTACH_DIR=/tmp/mutt_attachment
FILE_PATH=$1
CONTENT_TYPE=$2
FILE_NAME=$(basename $FILE_PATH)

# Create tmp attachment directory if it doesn't exist
if [ ! -d /tmp/mutt_attachment ]; then
  mkdir /tmp/mutt_attachment
fi

case $CONTENT_TYPE in
  text/html )
    FILE_TYPE='html'
    ;;
  application/pdf )
    FILE_TYPE = 'pdf'
  *)
    FILE_TYPE='txt'
    ;;
esac


# Copy file so we don't lose it once neomutt deletes the original copy
cp "$FILE_PATH" "$TMP_MUTT_ATTACH_DIR/$FILE_NAME.$FILE_TYPE"


# Default to use xdg-open
OS=$(uname -s)
if [[ $OS == 'Linux' ]]; then
    case $FILE_TYPE in
      html )
        OPEN_WITH_PROG=xdg-open
        ;;
      pdf )
        OPEN_WITH_PROG=zathura
        ;;
      *)
        OPEN_WITH_PROG=xdg-open
    esac
elif [[ $OS == 'Darwin' ]]; then
    case $FILE_TYPE in
      html )
        OPEN_WITH_PROG=$(open -a /Applications/qutebrowser.app/Contents/MacOS/qutebrowser)
        ;;
      pdf )
        OPEN_WITH_PROG=$(open -a /Applications/Adobe Acrobat Reader DC.app/Contents/MacOS/AdobeReader)
        ;;
      *)
        OPEN_WITH_PROG=open
    esac
else 
  echo 'Cannot determine what to do with $OS. Aborting'
  exit 1
fi
$OPEN_WITH_PROG "$TMP_MUTT_ATTACH_DIR/$FILE_NAME.$FILE_TYPE"
PROG=$(basename $OPEN_WITH_PROG)
echo "Opening with \"$PROG\""
