-- Goal
--require'nvim-fzf'.setup {
--  mappings = {
--    n = {
--      ["<C-p>"] = "lua require('nvim-fzf').git"
--    }
--  }
--}

--Temp
--vim.api.nvim_set_keymap('n', '<Leader>p', "<cmd>lua require('nvim-fzf.git')()<cr>", { noremap = true, silent = true })
